# Default values for mysql-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: tiswanso
tag: sr-example
pullPolicy: Always

nsm:
  serviceName: example

ipam:
  prefixPool: 192.170.0.0/16

global:
  
replicaCount: 1

nameOverride: ""
fullnameOverride: ""


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
